project_name: secnginx

builds:
  - env:
      - CGO_ENABLED=0
    binary: secnginx
    goos:
    - linux
    goarch:
    - amd64
    - 386
    - arm
    - arm64
    goarm:
    - 7

archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    linux: Linux
    386: i386
    amd64: x86_64
  files:
    - LICENSE
    - README.md
    - files/*
    - nginx/**/*
    - config.toml
checksum:
    name_template: 'checksums.txt'
