[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.1.0"

[[constraint]]
  name = "github.com/mholt/archiver"
  version = "2.0.0"

[[constraint]]
  name = "github.com/src-d/go-git"
  version = "3.2.0"
